steps:
  # Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/codesentry', '.']
  
  # Push da imagem para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/codesentry']

# Imagens que serão criadas
images:
  - 'gcr.io/$PROJECT_ID/codesentry'

# Timeout do build (10 minutos)
timeout: '600s'

# Opções de build
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8' 