version: '3.8'

services:
  codesentry-dev:
    build: .
    container_name: codesentry-dev
    ports:
      - "3000:8080"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=8080
    volumes:
      # Hot reload: monta o código fonte
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
