version: '3.8'

services:
  codesentry:
    build: .
    container_name: codesentry-app
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    # Remove volumes para comportamento similar ao docker run --rm
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    stdin_open: true
    tty: true
    # Auto-remove container quando parar (similar ao --rm)
    restart: "no"
