version: '3.8'

services:
  codesentry-dev:
    build: .
    container_name: codesentry-dev
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      # Para desenvolvimento: monta o código fonte
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    restart: "no"
    # Para desenvolvimento, pode querer expor uma porta
    # ports:
    #   - "3000:3000"
